#ifndef UBUNTUDOWNLOADMANAGERCLIENT_GLOBAL_H
#define UBUNTUDOWNLOADMANAGERCLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UBUNTUDOWNLOADMANAGERCLIENT_LIBRARY)
#  define UBUNTUDOWNLOADMANAGERCLIENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UBUNTUDOWNLOADMANAGERCLIENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UBUNTUDOWNLOADMANAGERCLIENT_GLOBAL_H
