#ifndef UDMPRIVCOMMON_GLOBAL_H
#define UDMPRIVCOMMON_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UDMPRIVCOMMON_LIBRARY)
#  define UDMPRIVCOMMONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UDMPRIVCOMMONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UDMPRIVCOMMON_GLOBAL_H
