/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.canonical.applications.download_manager.xml -p manager_interface -c ManagerInterface
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "manager_interface.h"

/*
 * Implementation of interface class ManagerInterface
 */

namespace Ubuntu {

namespace DownloadManager {

ManagerInterface::ManagerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ManagerInterface::~ManagerInterface()
{
}

}  // Ubuntu

}  // DownloadManager
