/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c PropertiesAdaptor -a properties_adaptor.h:properties_adaptor.cpp org.freedesktop.dBus.properties.xml
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "properties_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class PropertiesAdaptor
 */

PropertiesAdaptor::PropertiesAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

PropertiesAdaptor::~PropertiesAdaptor()
{
    // destructor
}

QVariant PropertiesAdaptor::Get(const QString &interface_name, const QString &property_name)
{
    // handle method call org.freedesktop.DBus.Properties.Get
    QVariant value;
    QMetaObject::invokeMethod(parent(), "get", Q_RETURN_ARG(QVariant, value), Q_ARG(QString, interface_name), Q_ARG(QString, property_name));
    return value;
}

QVariantMap PropertiesAdaptor::GetAll(const QString &interface_name)
{
    // handle method call org.freedesktop.DBus.Properties.GetAll
    QVariantMap properties;
    QMetaObject::invokeMethod(parent(), "getAll", Q_RETURN_ARG(QVariantMap, properties), Q_ARG(QString, interface_name));
    return properties;
}

void PropertiesAdaptor::Set(const QString &interface_name, const QString &property_name, const QVariant &value)
{
    // handle method call org.freedesktop.DBus.Properties.Set
    QMetaObject::invokeMethod(parent(), "set", Q_ARG(QString, interface_name), Q_ARG(QString, property_name), Q_ARG(QVariant, value));
}

