/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c PropertiesAdaptor -a properties_adaptor.h:properties_adaptor.cpp org.freedesktop.dBus.properties.xml
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef PROPERTIES_ADAPTOR_H_1410177568
#define PROPERTIES_ADAPTOR_H_1410177568

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include <ubuntu/download_manager/metatypes.h>

QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.DBus.Properties
 */
class PropertiesAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.DBus.Properties")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.DBus.Properties\">\n"
"    <method name=\"Get\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"interface_name\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"property_name\"/>\n"
"      <arg direction=\"out\" type=\"v\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"GetAll\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"interface_name\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"out\" type=\"a{sv}\" name=\"properties\"/>\n"
"    </method>\n"
"    <method name=\"Set\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"interface_name\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"property_name\"/>\n"
"      <arg direction=\"in\" type=\"v\" name=\"value\"/>\n"
"    </method>\n"
"    <signal name=\"PropertiesChanged\">\n"
"      <arg type=\"s\" name=\"interface_name\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"      <arg type=\"a{sv}\" name=\"changed_properties\"/>\n"
"      <arg type=\"as\" name=\"invalidated_properties\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    PropertiesAdaptor(QObject *parent);
    virtual ~PropertiesAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QVariant Get(const QString &interface_name, const QString &property_name);
    QVariantMap GetAll(const QString &interface_name);
    void Set(const QString &interface_name, const QString &property_name, const QVariant &value);
Q_SIGNALS: // SIGNALS
    void PropertiesChanged(const QString &interface_name, const QVariantMap &changed_properties, const QStringList &invalidated_properties);
};

#endif
