#ifndef UBUNTUDOWNLOADMANAGERTESTLIB_GLOBAL_H
#define UBUNTUDOWNLOADMANAGERTESTLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UBUNTUDOWNLOADMANAGERTESTLIB_LIBRARY)
#  define UBUNTUDOWNLOADMANAGERTESTLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UBUNTUDOWNLOADMANAGERTESTLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UBUNTUDOWNLOADMANAGERTESTLIB_GLOBAL_H
