/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c ApplicationDownloadAdaptor -a /home/mandel/Canonical/junk/app-downloader/app-downloader/app-downloader-lib/application_download_adaptor.h:/home/mandel/Canonical/junk/app-downloader/app-downloader/app-downloader-lib/application_download_adaptor.cpp /home/mandel/Canonical/junk/app-downloader/app-downloader/app-downloader-lib/com.canonical.applications.application_download.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "/home/mandel/Canonical/junk/app-downloader/app-downloader/app-downloader-lib/application_download_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ApplicationDownloadAdaptor
 */

ApplicationDownloadAdaptor::ApplicationDownloadAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ApplicationDownloadAdaptor::~ApplicationDownloadAdaptor()
{
    // destructor
}

void ApplicationDownloadAdaptor::cancel()
{
    // handle method call com.canonical.applications.ApplicationDownload.cancel
    QMetaObject::invokeMethod(parent(), "cancel");
}

void ApplicationDownloadAdaptor::pause()
{
    // handle method call com.canonical.applications.ApplicationDownload.pause
    QMetaObject::invokeMethod(parent(), "pause");
}

void ApplicationDownloadAdaptor::resume()
{
    // handle method call com.canonical.applications.ApplicationDownload.resume
    QMetaObject::invokeMethod(parent(), "resume");
}

void ApplicationDownloadAdaptor::start()
{
    // handle method call com.canonical.applications.ApplicationDownload.start
    QMetaObject::invokeMethod(parent(), "start");
}

