/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c ApplicationDownloadAdaptor -a application_download_adaptor.h:application_download_adaptor.cpp com.canonical.applications.application_download.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "application_download_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ApplicationDownloadAdaptor
 */

ApplicationDownloadAdaptor::ApplicationDownloadAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ApplicationDownloadAdaptor::~ApplicationDownloadAdaptor()
{
    // destructor
}

QString ApplicationDownloadAdaptor::applicationId()
{
    // handle method call com.canonical.applications.ApplicationDownload.applicationId
    QString id;
    QMetaObject::invokeMethod(parent(), "applicationId", Q_RETURN_ARG(QString, id));
    return id;
}

QString ApplicationDownloadAdaptor::applicationName()
{
    // handle method call com.canonical.applications.ApplicationDownload.applicationName
    QString name;
    QMetaObject::invokeMethod(parent(), "applicationName", Q_RETURN_ARG(QString, name));
    return name;
}

void ApplicationDownloadAdaptor::cancel()
{
    // handle method call com.canonical.applications.ApplicationDownload.cancel
    QMetaObject::invokeMethod(parent(), "cancel");
}

QVariantMap ApplicationDownloadAdaptor::metadata()
{
    // handle method call com.canonical.applications.ApplicationDownload.metadata
    QVariantMap data;
    QMetaObject::invokeMethod(parent(), "metadata", Q_RETURN_ARG(QVariantMap, data));
    return data;
}

void ApplicationDownloadAdaptor::pause()
{
    // handle method call com.canonical.applications.ApplicationDownload.pause
    QMetaObject::invokeMethod(parent(), "pause");
}

uint ApplicationDownloadAdaptor::progress()
{
    // handle method call com.canonical.applications.ApplicationDownload.progress
    uint received;
    QMetaObject::invokeMethod(parent(), "progress", Q_RETURN_ARG(uint, received));
    return received;
}

void ApplicationDownloadAdaptor::resume()
{
    // handle method call com.canonical.applications.ApplicationDownload.resume
    QMetaObject::invokeMethod(parent(), "resume");
}

void ApplicationDownloadAdaptor::start()
{
    // handle method call com.canonical.applications.ApplicationDownload.start
    QMetaObject::invokeMethod(parent(), "start");
}

uint ApplicationDownloadAdaptor::totalSize()
{
    // handle method call com.canonical.applications.ApplicationDownload.totalSize
    uint total;
    QMetaObject::invokeMethod(parent(), "totalSize", Q_RETURN_ARG(uint, total));
    return total;
}

