/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DownloaderAdaptor -a /home/mandel/Canonical/junk/app-downloader/app-downloader/app-downloader-lib/downloader_adaptor.h:/home/mandel/Canonical/junk/app-downloader/app-downloader/app-downloader-lib/downloader_adaptor.cpp /home/mandel/Canonical/junk/app-downloader/app-downloader/app-downloader-lib/com.canonical.applications.downloader.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "/home/mandel/Canonical/junk/app-downloader/app-downloader/app-downloader-lib/downloader_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DownloaderAdaptor
 */

DownloaderAdaptor::DownloaderAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DownloaderAdaptor::~DownloaderAdaptor()
{
    // destructor
}

QDBusObjectPath DownloaderAdaptor::createDownload(const QString &url)
{
    // handle method call com.canonical.applications.Downloader.createDownload
    QDBusObjectPath download;
    QMetaObject::invokeMethod(parent(), "createDownload", Q_RETURN_ARG(QDBusObjectPath, download), Q_ARG(QString, url));
    return download;
}

QDBusObjectPath DownloaderAdaptor::createDownloadMd4(const QString &url, const QString &hash)
{
    // handle method call com.canonical.applications.Downloader.createDownloadMd4
    QDBusObjectPath download;
    QMetaObject::invokeMethod(parent(), "createDownloadMd4", Q_RETURN_ARG(QDBusObjectPath, download), Q_ARG(QString, url), Q_ARG(QString, hash));
    return download;
}

QDBusObjectPath DownloaderAdaptor::createDownloadMd5(const QString &url, const QString &hash)
{
    // handle method call com.canonical.applications.Downloader.createDownloadMd5
    QDBusObjectPath download;
    QMetaObject::invokeMethod(parent(), "createDownloadMd5", Q_RETURN_ARG(QDBusObjectPath, download), Q_ARG(QString, url), Q_ARG(QString, hash));
    return download;
}

QDBusObjectPath DownloaderAdaptor::createDownloadSha1(const QString &url, const QString &hash)
{
    // handle method call com.canonical.applications.Downloader.createDownloadSha1
    QDBusObjectPath download;
    QMetaObject::invokeMethod(parent(), "createDownloadSha1", Q_RETURN_ARG(QDBusObjectPath, download), Q_ARG(QString, url), Q_ARG(QString, hash));
    return download;
}

QDBusObjectPath DownloaderAdaptor::createDownloadSha224(const QString &url, const QString &hash)
{
    // handle method call com.canonical.applications.Downloader.createDownloadSha224
    QDBusObjectPath download;
    QMetaObject::invokeMethod(parent(), "createDownloadSha224", Q_RETURN_ARG(QDBusObjectPath, download), Q_ARG(QString, url), Q_ARG(QString, hash));
    return download;
}

QDBusObjectPath DownloaderAdaptor::createDownloadSha256(const QString &url, const QString &hash)
{
    // handle method call com.canonical.applications.Downloader.createDownloadSha256
    QDBusObjectPath download;
    QMetaObject::invokeMethod(parent(), "createDownloadSha256", Q_RETURN_ARG(QDBusObjectPath, download), Q_ARG(QString, url), Q_ARG(QString, hash));
    return download;
}

QDBusObjectPath DownloaderAdaptor::createDownloadSha384(const QString &url, const QString &hash)
{
    // handle method call com.canonical.applications.Downloader.createDownloadSha384
    QDBusObjectPath download;
    QMetaObject::invokeMethod(parent(), "createDownloadSha384", Q_RETURN_ARG(QDBusObjectPath, download), Q_ARG(QString, url), Q_ARG(QString, hash));
    return download;
}

QDBusObjectPath DownloaderAdaptor::createDownloadSha512(const QString &url, const QString &hash)
{
    // handle method call com.canonical.applications.Downloader.createDownloadSha512
    QDBusObjectPath download;
    QMetaObject::invokeMethod(parent(), "createDownloadSha512", Q_RETURN_ARG(QDBusObjectPath, download), Q_ARG(QString, url), Q_ARG(QString, hash));
    return download;
}

QList<QDBusObjectPath> DownloaderAdaptor::getAllDownloads()
{
    // handle method call com.canonical.applications.Downloader.getAllDownloads
    QList<QDBusObjectPath> downloads;
    QMetaObject::invokeMethod(parent(), "getAllDownloads", Q_RETURN_ARG(QList<QDBusObjectPath>, downloads));
    return downloads;
}

