/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DownloaderAdaptor -a downloader_adaptor.h:downloader_adaptor.cpp com.canonical.applications.downloader.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "downloader_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DownloaderAdaptor
 */

DownloaderAdaptor::DownloaderAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DownloaderAdaptor::~DownloaderAdaptor()
{
    // destructor
}

QDBusObjectPath DownloaderAdaptor::createDownload(const QString &id, const QString &name, const QString &url)
{
    // handle method call com.canonical.applications.Downloader.createDownload
    QDBusObjectPath download;
    QMetaObject::invokeMethod(parent(), "createDownload", Q_RETURN_ARG(QDBusObjectPath, download), Q_ARG(QString, id), Q_ARG(QString, name), Q_ARG(QString, url));
    return download;
}

QDBusObjectPath DownloaderAdaptor::createDownloadWithHash(const QString &id, const QString &name, const QString &url, const QString &algorithm, const QString &hash)
{
    // handle method call com.canonical.applications.Downloader.createDownloadWithHash
    QDBusObjectPath download;
    QMetaObject::invokeMethod(parent(), "createDownloadWithHash", Q_RETURN_ARG(QDBusObjectPath, download), Q_ARG(QString, id), Q_ARG(QString, name), Q_ARG(QString, url), Q_ARG(QString, algorithm), Q_ARG(QString, hash));
    return download;
}

QList<QDBusObjectPath> DownloaderAdaptor::getAllDownloads()
{
    // handle method call com.canonical.applications.Downloader.getAllDownloads
    QList<QDBusObjectPath> downloads;
    QMetaObject::invokeMethod(parent(), "getAllDownloads", Q_RETURN_ARG(QList<QDBusObjectPath>, downloads));
    return downloads;
}

