/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.canonical.applications.download.xml -i metatypes.h -p download_interface -c DownloadInterface
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef DOWNLOAD_INTERFACE_H_1392136772
#define DOWNLOAD_INTERFACE_H_1392136772

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include <ubuntu/download_manager/metatypes.h>

/*
 * Proxy class for interface com.canonical.applications.Download
 */
class DownloadInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.canonical.applications.Download"; }

public:
    DownloadInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~DownloadInterface();

    Q_PROPERTY(QString ClickPackage READ clickPackage)
    inline QString clickPackage() const
    { return qvariant_cast< QString >(property("ClickPackage")); }

    Q_PROPERTY(bool ShowInIndicator READ showInIndicator)
    inline bool showInIndicator() const
    { return qvariant_cast< bool >(property("ShowInIndicator")); }

    Q_PROPERTY(QString Title READ title)
    inline QString title() const
    { return qvariant_cast< QString >(property("Title")); }

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> allowGSMDownload(bool allowed)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(allowed);
        return asyncCallWithArgumentList(QLatin1String("allowGSMDownload"), argumentList);
    }

    inline QDBusPendingReply<> cancel()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("cancel"), argumentList);
    }

    inline QDBusPendingReply<StringMap> headers()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("headers"), argumentList);
    }

    inline QDBusPendingReply<bool> isGSMDownloadAllowed()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("isGSMDownloadAllowed"), argumentList);
    }

    inline QDBusPendingReply<QVariantMap> metadata()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("metadata"), argumentList);
    }

    inline QDBusPendingReply<> pause()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("pause"), argumentList);
    }

    inline QDBusPendingReply<qulonglong> progress()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("progress"), argumentList);
    }

    inline QDBusPendingReply<> resume()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("resume"), argumentList);
    }

    inline QDBusPendingReply<> setDestinationDir(const QString &path)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(path);
        return asyncCallWithArgumentList(QLatin1String("setDestinationDir"), argumentList);
    }

    inline QDBusPendingReply<> setHeaders(StringMap headers)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(headers);
        return asyncCallWithArgumentList(QLatin1String("setHeaders"), argumentList);
    }

    inline QDBusPendingReply<> setMetadata(const QVariantMap &data)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(data);
        return asyncCallWithArgumentList(QLatin1String("setMetadata"), argumentList);
    }

    inline QDBusPendingReply<> setThrottle(qulonglong speed)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(speed);
        return asyncCallWithArgumentList(QLatin1String("setThrottle"), argumentList);
    }

    inline QDBusPendingReply<> start()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("start"), argumentList);
    }

    inline QDBusPendingReply<qulonglong> throttle()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("throttle"), argumentList);
    }

    inline QDBusPendingReply<qulonglong> totalSize()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("totalSize"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void authError(AuthErrorStruct error);
    void canceled(bool success);
    void error(const QString &error);
    void finished(const QString &path);
    void hashError(HashErrorStruct error);
    void httpError(HttpErrorStruct error);
    void networkError(NetworkErrorStruct error);
    void paused(bool success);
    void processError(ProcessErrorStruct error);
    void processing(const QString &path);
    void progress(qulonglong received, qulonglong total);
    void resumed(bool success);
    void started(bool success);
};

namespace com {
  namespace canonical {
    namespace applications {
      typedef ::DownloadInterface Download;
    }
  }
}
#endif
