/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DownloadManagerAdaptor -a download_manager_adaptor.h:download_manager_adaptor.cpp com.canonical.applications.download_manager.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "download_manager_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DownloadManagerAdaptor
 */

DownloadManagerAdaptor::DownloadManagerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DownloadManagerAdaptor::~DownloadManagerAdaptor()
{
    // destructor
}

QDBusObjectPath DownloadManagerAdaptor::createDownload(const QString &url, const QVariantMap &metadata, const QVariantMap &headers)
{
    // handle method call com.canonical.applications.DownloaderManager.createDownload
    QDBusObjectPath download;
    QMetaObject::invokeMethod(parent(), "createDownload", Q_RETURN_ARG(QDBusObjectPath, download), Q_ARG(QString, url), Q_ARG(QVariantMap, metadata), Q_ARG(QVariantMap, headers));
    return download;
}

QDBusObjectPath DownloadManagerAdaptor::createDownloadWithHash(const QString &url, const QString &algorithm, const QString &hash, const QVariantMap &metadata, const QVariantMap &headers)
{
    // handle method call com.canonical.applications.DownloaderManager.createDownloadWithHash
    QDBusObjectPath download;
    QMetaObject::invokeMethod(parent(), "createDownloadWithHash", Q_RETURN_ARG(QDBusObjectPath, download), Q_ARG(QString, url), Q_ARG(QString, algorithm), Q_ARG(QString, hash), Q_ARG(QVariantMap, metadata), Q_ARG(QVariantMap, headers));
    return download;
}

QList<QDBusObjectPath> DownloadManagerAdaptor::getAllDownloads()
{
    // handle method call com.canonical.applications.DownloaderManager.getAllDownloads
    QList<QDBusObjectPath> downloads;
    QMetaObject::invokeMethod(parent(), "getAllDownloads", Q_RETURN_ARG(QList<QDBusObjectPath>, downloads));
    return downloads;
}

QList<QDBusObjectPath> DownloadManagerAdaptor::getAllDownloadsWithMetadata(const QString &name, const QString &value)
{
    // handle method call com.canonical.applications.DownloaderManager.getAllDownloadsWithMetadata
    QList<QDBusObjectPath> downloads;
    QMetaObject::invokeMethod(parent(), "getAllDownloadsWithMetadata", Q_RETURN_ARG(QList<QDBusObjectPath>, downloads), Q_ARG(QString, name), Q_ARG(QString, value));
    return downloads;
}

