/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c UploadManagerAdaptor -a upload_manager_adaptor.h:upload_manager_adaptor.cpp -i metatypes.h com.canonical.applications.upload_manager.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef UPLOAD_MANAGER_ADAPTOR_H_1392930728
#define UPLOAD_MANAGER_ADAPTOR_H_1392930728

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include <ubuntu/upload_manager/metatypes.h>

QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

namespace Ubuntu {

using namespace Errors;

namespace UploadManager {

/*
 * Adaptor class for interface com.canonical.applications.UploadManager
 */
class UploadManagerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.canonical.applications.UploadManager")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.canonical.applications.UploadManager\">\n"
"    <method name=\"createUpload\">\n"
"      <annotation value=\"UploadStruct\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"      <arg direction=\"in\" type=\"(ssa{sv}a{ss})\" name=\"upload\"/>\n"
"      <arg direction=\"out\" type=\"o\" name=\"uploadPath\"/>\n"
"    </method>\n"
"    <method name=\"createMmsUpload\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"url\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"file\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"hostname\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"port\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"username\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"password\"/>\n"
"      <arg direction=\"out\" type=\"o\" name=\"uploadPath\"/>\n"
"    </method>\n"
"    <method name=\"getAllUploads\">\n"
"      <arg direction=\"out\" type=\"ao\" name=\"uploads\"/>\n"
"    </method>\n"
"    <method name=\"getAllUploadsWithMetadata\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"value\"/>\n"
"      <arg direction=\"out\" type=\"ao\" name=\"uploads\"/>\n"
"    </method>\n"
"    <method name=\"setDefaultThrottle\">\n"
"      <arg direction=\"in\" type=\"t\" name=\"speed\"/>\n"
"    </method>\n"
"    <method name=\"defaultThrottle\">\n"
"      <arg direction=\"out\" type=\"t\" name=\"speed\"/>\n"
"    </method>\n"
"    <method name=\"allowMobileUpload\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"allowed\"/>\n"
"    </method>\n"
"    <method name=\"isMobileUploadAllowed\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"allowed\"/>\n"
"    </method>\n"
"    <method name=\"exit\"/>\n"
"    <signal name=\"uploadCreated\">\n"
"      <arg direction=\"out\" type=\"o\" name=\"path\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    UploadManagerAdaptor(QObject *parent);
    virtual ~UploadManagerAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void allowMobileUpload(bool allowed);
    QDBusObjectPath createMmsUpload(const QString &url, const QString &file, const QString &hostname, int port, const QString &username, const QString &password);
    QDBusObjectPath createUpload(UploadStruct upload);
    qulonglong defaultThrottle();
    void exit();
    QList<QDBusObjectPath> getAllUploads();
    QList<QDBusObjectPath> getAllUploadsWithMetadata(const QString &name, const QString &value);
    bool isMobileUploadAllowed();
    void setDefaultThrottle(qulonglong speed);
Q_SIGNALS: // SIGNALS
    void uploadCreated(const QDBusObjectPath &path);
};

}  // UploadManager

}  // Ubuntu
#endif
