#ifndef UBUNTUUPLOADMANAGERCOMMON_GLOBAL_H
#define UBUNTUUPLOADMANAGERCOMMON_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UBUNTUUPLOADMANAGERCOMMON_LIBRARY)
#  define UBUNTUUPLOADMANAGERCOMMONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UBUNTUUPLOADMANAGERCOMMONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UBUNTUUPLOADMANAGERCOMMON_GLOBAL_H
