#ifndef UDMTESTING_GLOBAL_H
#define UDMTESTING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UDMTESTING_LIBRARY)
#  define UDMTESTINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UDMTESTINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UDMTESTING_GLOBAL_H
